### ISSUE TITLE
Seek support

### ISSUE THREAD

**Issue by mewmew** [mewkiz/flac#16]
From `flac.go`:

``` go
// TODO: Implement a Seek method.
```

Creating this issue to facilitate an open discussion on how we may implement audio seek support in the future. What do we need to keep in mind?
- Performance?
-  How should the API look like?
- Should we require a seek table to be present in the metadata? 
- Should we make use of the sync codes to seek when no seek table is present?
- Will we require the underlying stream to implement [io.Seeker](https://golang.org/pkg/io/#Seeker)?

Some notes from the [x/audio proposal](https://github.com/golang/go/issues/13432):

@rakyll wrote at https://github.com/golang/go/issues/13432#issuecomment-184853011

> Seeking is often expensive, we may adopt an io.ReadSeeker-like interface to make Seek a standalone operation to put some more emphasis on its cost.

**Comment by varyoo** [comment]
From the FLAC specifications: "SEEKTABLE: This is an optional block for storing seek points."

**Comment by mewmew** [comment]
A preliminary implementation exists in the [dev branch](https://github.com/mewkiz/flac/tree/dev) for anyone brave enough to try it out :)

**Comment by tslocum** [comment]
I am glad to review and test the seek branch but I may also be able to contribute code changes.  What work remains for seek support to be merged?

**Comment by mewmew** [comment]
> I am glad to review and test the seek branch but I may also be able to contribute code changes. What work remains for seek support to be merged?

Hi @tslocum,

I think @karlek has the best grasp of the seek code. He'll be out for the weekend, but should be back by next week.

Also, if you are interested in working on getting the seek code production ready that's great! We would definitely welcome such a contribution :)

Cheers,
Henry & Robin

**Comment by karlek** [comment]
Hi @tslocum 

I apologize for my late response.

After looking at the code, I realize it's been a long time since it's was written and it's not up-to-par with the rest of the code base and should not be used. Therefore, if you'd like to contribute and implement seeking we would be very grateful.

Henry

**Comment by karlek** [comment]
Fixed in #44 by @cswank, great job! :raised_hands:
