### ISSUE TITLE
[Feature Request] Add the ability to skip ID3 tags/ID3 data

### ISSUE THREAD

**Issue by jcjordyn130** [mewkiz/flac#20]
The library expects a flac signature but doesn't skip over ID3 data to try to find it.

**Comment by mewmew** [comment]
@karlek I'll leave this one to you :)

**Comment by mewmew** [comment]
@jcjordyn130 Do you have any test case for this that we could add? Preferable small in file size and if possible in the public domain (so we don't run into license issues).

**Comment by jcjordyn130** [comment]
Here's the audio file that made me open this PR, minus the audio data and with the tags set to generic values: https://transfer.sh/S3Aq7/id3.flac

**Comment by mewmew** [comment]
@jcjordyn130 Thanks for reporting the issue and for the tight feedback loop on resolving it :)

If you are working on audio development or like playing with these kinds of libraries, we'd be very interested for you to join our discussion in #19.

Cheers!
Henry and Robin

**Comment by jcjordyn130** [comment]
You're very welcome, and I think I will.=
