### ISSUE TITLE
Slight audio playback issues with some flac files depending on header block size?

### ISSUE THREAD

**Issue by mehrvarz** [mewkiz/flac#29]
Hi. Some of my flac files don't play back perfectly. The issue appears to depend on the block size in the header.
blockSize=12 results in frame.BlockSize=4096 which plays back perfectly.
blockSize=5 results in frame.BlockSize=4608 which comes out slightly scrambled.
Any idea what could be causing this? Thank you.

**Comment by mewmew** [comment]
Could you provide an example FLAC file that we may try to reproduce the issue with? Thanks!

/u & _

**Comment by mehrvarz** [comment]
The blockSize=5 flac files I own are most likely signed. Can't share those. I'll find alternative flac files with identical attributes and let you know.

**Comment by mehrvarz** [comment]
Hi, I was able to solve this issue. If you are interested, pls take a look at https://github.com/gordonklaus/portaudio/issues/23 and find the post (from 15 minutes ago) where I mention "unusual header block sizes". I think we can close this :-)

**Comment by mewmew** [comment]
> Hi, I was able to solve this issue. If you are interested, pls take a look at gordonklaus/portaudio#23 and find the post (from 15 minutes ago) where I mention "unusual header block sizes". I think we can close this :-)

Lovely to hear. I'll close this issue. Feel free to open a new issue if something else seems amiss with the flac decoding. And thanks for reporting!
