### ISSUE TITLE
Convert problem in the flac2wav

### ISSUE THREAD

**Issue by YoukeYu** [mewkiz/flac#38]
I don know how to deal with this problem `flac.parseStreamInfo: invalid FLAC signature; expected "fLaC" got "\xcf\xfa\xed\xfe`. When I try to convert a Flac file to wav, the terminal shows this. 

*It's strange that at first I succeeded* to convert one file, but after that, I couldn't succeed, even using the examples provided by the author 
Looking for the cause and solution.
Hopefully

**Comment by mewmew** [comment]
Hi @YoukeYu,

Hope you managed to solve the issue you mentioned. Since the FLAC signature was reported as wrong, try to verify that the input file is indeed a FLAC file.

This can be done by running:

```
$ flac -t foo.flac

flac 1.3.3

foo.flac: ok      
```

Cheers,
Robin

**Comment by YoukeYu** [comment]
Thanks for your reply.
I checked again and found that the format of my code is wrong.
thanks to wrong understanding of the Usage 'flac2wav [OPTION]... FILE.flac...'

Now it has been solved

very sorry to bother you.

**Comment by karlek** [comment]
No worries, we are happy to help if you have more questions. Thanks for using `mewkiz/flac`!
