### ISSUE TITLE
Error when downloading package

### ISSUE THREAD

**Issue by Keithcat1** [mewkiz/flac#39]
C:\py\e>go get github.com/mewkiz/flac
# github.com/mewkiz/flac
..\go\src\github.com\mewkiz\flac\encode.go:55:28: cannot use bw (type *bitio.Wri
ter) as type bitio.Writer in argument to encodeStreamInfo
..\go\src\github.com\mewkiz\flac\encode.go:59:24: cannot use bw (type *bitio.Wri
ter) as type bitio.Writer in argument to encodeBlock
..\go\src\github.com\mewkiz\flac\encode.go:98:29: cannot use bw (type *bitio.Wri
ter) as type bitio.Writer in argument to encodeStreamInfo
..\go\src\github.com\mewkiz\flac\encode_frame.go:69:27: cannot use bw (type *bit
io.Writer) as type bitio.Writer in argument to encodeSubframe
..\go\src\github.com\mewkiz\flac\encode_frame.go:120:57: cannot use bw (type *bi
tio.Writer) as type bitio.Writer in argument to encodeFrameHeaderBlockSize
..\go\src\github.com\mewkiz\flac\encode_frame.go:126:81: cannot use bw (type *bi
tio.Writer) as type bitio.Writer in argument to encodeFrameHeaderSampleRate
..\go\src\github.com\mewkiz\flac\encode_frame.go:132:37: cannot use bw (type *bi
tio.Writer) as type bitio.Writer in argument to encodeFrameHeaderChannels
..\go\src\github.com\mewkiz\flac\encode_frame.go:137:42: cannot use bw (type *bi
tio.Writer) as type bitio.Writer in argument to encodeFrameHeaderBitsPerSample
..\go\src\github.com\mewkiz\flac\encode_meta.go:154:25: cannot use bw (type biti
o.Writer) as type io.Writer in argument to binary.Write:
        bitio.Writer does not implement io.Writer (Write method has pointer rece
iver)
..\go\src\github.com\mewkiz\flac\encode_meta.go:183:24: cannot use bw (type biti
o.Writer) as type io.Writer in argument to binary.Write:
        bitio.Writer does not implement io.Writer (Write method has pointer rece
iver)
..\go\src\github.com\mewkiz\flac\encode_meta.go:183:24: too many errors

C:\py\e>

**Comment by spbkaizo** [comment]
Hiya,

Yeah.... All the deps are out of sync.  I'm looking into it, but it's not currently a priority.  Basically I'd need to fix the flac library out of sync.

You should be able to do a build by git cloning the repo, and it'll use the included vendor folder.

S.

--
https://kz.uni.cx

________________________________

**Comment by mewmew** [comment]
@Keithcat1 and @spbkaizo, thanks for reporting and following up on this issue.

As of 0b3d4b0db50be2bb0eefcf2cc2b9a5da413baedb, the dependencies of `flac` have been updated to their latest versions (using `go get -u ./...`). As such, using `go get github.com/mewkiz/flac` should now work again both in modules and non-modules mode. A new release has also been tagged, the v1.0.6 release. See the associated [release notes](https://github.com/mewkiz/flac#changes).

I'll close this issue for now. If the issue persists, feel free to reopen.

Cheers,
Robin
