### ISSUE TITLE
bug: HasFixedBlockSize

### ISSUE THREAD

**Issue by sdidyk** [mewkiz/flac#8]
HasFixedBlockSize field has inverted state.

from https://xiph.org/flac/format.html#frame_header
```
0 : fixed-blocksize stream; frame header encodes the frame number
1 : variable-blocksize stream; frame header encodes the sample number
```

but in code:
```
	// 1 bit: HasFixedBlockSize.
	x, err = br.Read(1)
	if err != nil {
		return unexpected(err)
	}
	if x != 0 {
		frame.HasFixedBlockSize = true
	}
```

**Comment by mewmew** [comment]
Thanks for the heads up! Do you wanna prepare a pull request, or would you prefer me to make the change?

Cheers /u

**Comment by sdidyk** [comment]
Of course, it's oneliner.
